api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from api.views import *
from rest_framework.authtoken.views import obtain_auth_token

router=DefaultRouter()
router.register('category',CategoryView,basename="categories")
router.register('products',ProductView,basename="products")
router.register('accounts/signup',UserRegistrationView,basename='register')
router.register('carts',CartsView,basename='carts')




urlpatterns=[
                path('accounts/token', obtain_auth_token),

            ]+router.urls

customer/urls.py
from django.urls import path
from customer import views

urlpatterns=[
    path("login",views.LoginView.as_view(),name='login'),
    path("register", views.RageistrationView.as_view(), name='register'),
    path("home", views.HomeView.as_view(), name='home'),
    path("products/<int:id>/",views.ProductDetailView.as_view(),name="product-detail"),
    path('products/<int:id>/carts/add',views.AddToCartView.as_view(),name="addto-cart"),
    path("carts/all",views.MyCartView.as_view(),name="mycart"),
    path('carts/remove/<int:id>',views.CartRemoveView.as_view(),name='cart-remove'),
    path('signout',views.SignOutView.as_view(),name="signout"),
    path("carts/placeorder/<int:cid>/<int:pid>",views.PlaceOrderView.as_view(),name='place-order')
]

futurestore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1',include("api.urls")),
    path('',include('customer.urls')),
    path('owner/',include("owner.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.db import models

# Create your models here.

owner/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator,MaxValueValidator


# Create your models here.

class Categories(models.Model):
    category_name=models.CharField(max_length=120,unique=True)
    is_active=models.BooleanField(default=True)

    def __str__(self):
        return self.category_name


class Products(models.Model):
    product_name=models.CharField(max_length=120,unique=True)
    category=models.ForeignKey(Categories,on_delete=models.CASCADE)
    image=models.ImageField( upload_to="Images", null=True)
    price=models.PositiveIntegerField()
    description=models.CharField( max_length=250,null=True)

    def __str__(self):
        return self.product_name


class Carts(models.Model):
    product=models.ForeignKey(Products, on_delete=models.CASCADE)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    created_date=models.DateTimeField(auto_now_add=True,null=True)
    options=(
        ("incart","incart"),
       ( "order placed","order placed"),
        ("cancelled","cancelled"),

    )
    status=models.CharField(max_length=120,choices=options,default="incart")
    quantity=models.PositiveIntegerField(default=1)

class Orders(models.Model):
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    created_date=models.DateTimeField(auto_now_add=True,null=True)
    options=(
        ("order-placed","order-placed"),
        ("dispatched","dispatched"),
        ("in-transit","in-transit"),
        ("delivered","delivered"),
        ("cancelled","cancelled")
    )
    status=models.CharField(max_length=120,choices=options,default="order-placed")
    delivery_address=models.CharField(max_length=120,null=True)
    expected_date=models.DateField(null=True)



class Reviews(models.Model):
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    comments=models.CharField(max_length=120)
    rating=models.PositiveIntegerField([MinValueValidator(1),MaxValueValidator(5)])


    

customer/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from owner.models import Carts
class LoginForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control"}))

class UserRegistrationForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control"}))
    password2=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control"}))

    class Meta:
        model=User
        fields=[
            "username",
            "password1",
            "password2",
            "email"
        ]
        widgets={
            "username":forms.TextInput(attrs={"class":"form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"})

        }


class CartForm(forms.Form):
    quantity=forms.IntegerField(widget=forms.NumberInput(attrs={"class":"form-control"}))


class OrderForm(forms.Form):
    delivery_address=forms.CharField(widget=forms.Textarea(attrs={"class":"form-control"}))

customer/views.py
from django.shortcuts import render,redirect
from owner.models import *
from django.contrib.auth.models import User
from django.views.generic import CreateView,TemplateView,View,FormView,DetailView,ListView,UpdateView
from customer import forms
from django.urls import reverse_lazy
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.core.mail import send_mail

# Create your views here.

class RageistrationView(CreateView):
    form_class = forms.UserRegistrationForm
    template_name = "registration.html"
    success_url = reverse_lazy("login")

class LoginView(FormView):
    template_name = "login.html"
    form_class = forms.LoginForm

    def post(self,request,*args,**kwargs):
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data.get("username")
            password=form.cleaned_data.get("password")
            user=authenticate(request,username=username,password=password)
            if user:
                login(request,user)
                if request.user.is_superuser:
                    messages.success(request, "")
                    return redirect("dashboard")
                else:
                    return redirect("home")
            else:
                messages.error(request, "invalid credentials")
                return render(request,"login.html",{"form":form})

class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        all_products=Products.objects.all()
        context["products"]=all_products
        return context


class ProductDetailView(DetailView):
    template_name = "product-detail.html"
    model = Products
    context_object_name = "product"
    pk_url_kwarg = "id"

class AddToCartView(FormView):
    template_name = "addto-cart.html"
    form_class = forms.CartForm


    def get(self,request,*args,**kwargs):
        id=kwargs.get("id")
        product=Products.objects.get(id=id)
        return render(request,self.template_name,{"form":forms.CartForm,"product":product})

    def post(self,request,*args,**kwargs):
        id = kwargs.get("id")
        product = Products.objects.get(id=id)
        quantity=request.POST.get("quantity")
        user=request.user
        Carts.objects.create(product=product,user=user,quantity=quantity)
        messages.success(self.request, "")
        return redirect("home")


class MyCartView(ListView):
    model = Carts
    template_name = "cart-list.html"
    context_object_name = "carts"

    def get_queryset(self):
        return Carts.objects.filter(user=self.request.user).exclude(status="cancelled").order_by("-created_date")



class CartRemoveView(ListView):
    template_name = "cart-remove.html"
    form_class = forms.CartForm
    context_object_name = "carts"

    def get_queryset(self):
        id=self.kwargs.get("id")
        cart=Carts.objects.get(id=id)
        cart.status="cancelled"
        cart.delete()
        messages.success(self.request,"removed successfully")
        return Carts.objects.filter(user=self.request.user).exclude(status="cancelled").order_by("-created_date")



class SignOutView(View):
    def get(self,request,*args,**kwargs):
        logout(request)
        return redirect("signin")


class PlaceOrderView(FormView):
    template_name = "place-order.html"
    form_class = forms.OrderForm

    def post(self,request,*args,**kwargs):
        cart_id=kwargs.get("cid")
        product_id=kwargs.get("pid")
        cart=Carts.objects.get(id=cart_id)
        product=Products.objects.get(id=product_id)
        user=request.user
        delivery_address=request.POST.get("delivery_address")
        Orders.objects.create(product=product,user=user,delivery_address=delivery_address)
        cart.status="order placed"
        cart.save()
        return redirect("home")

customer/templates/addto-cart - Copy.html
{%extends 'base.html'%}
{%block body_block%}
<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
             <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{product.image.url }}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">
                                        {{product.product_name}}

                                    </h5>
                                    <!-- Product price-->
                                    ${{product.price}}
                                    <p>{{product.description}}</p>
                                    <p>{{product.category}}</p>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            </div>
                        </div>
                    </div>
        </div>
        <div class="col-2"></div>
    </div>
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="post">
                {%csrf_token%}
                {{form.as_p}}
                <button type="submit">Add</button>
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>
{%endblock%}

customer/templates/addto-cart.html
{%extends 'base.html'%}
{%block body_block%}
<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
             <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{product.image.url }}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">
                                        {{product.product_name}}

                                    </h5>
                                    <!-- Product price-->
                                    ${{product.price}}
                                    <p>{{product.description}}</p>
                                    <p>{{product.category}}</p>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            </div>
                        </div>
                    </div>
        </div>
        <div class="col-2"></div>
    </div>
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="post">
                {%csrf_token%}
                {{form.as_p}}
                <button type="submit">Add</button>
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>
{%endblock%}

customer/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
    <head>

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Shop Homepage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{%static 'assets/favicon.ico'%}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%static 'css/styles.css'%}" rel="stylesheet" />
        <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    </head>

    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">Future Store</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{%url 'home'%}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="{%url 'login'%}">LogOut</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <a href="{%url 'mycart'%}">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill">
                                {{request.user.carts_set.all.count}}
                            </span>
                        </a>


                    </form>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Future Store</h1>
<!--                    <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>-->
                </div>
            </div>
        </header>

      <section class="py-5">

            {%block body_block%}
          {%endblock%}
      </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{%static 'js/scripts.js' %}"></script>
    </body>
</html>

customer/templates/cart-list.html
{%extends 'base.html'%}
{%block body_block%}
<div class="container-fluid">
    <div class="row">
        {%for cart in carts%}
        <div class="col-4"></div>
        <div class="col-4">
            <div class="card h-100">
                <!-- Product image-->
                <img class="card-img-top" src="{{cart.product.image.url}}" height="100%" width="100%" alt="..."/>
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{cart.product.product_name}}</h5>
                        <!-- Product price-->
                        Rs.{{cart.product.price}}/-
                    </div>
                </div>
            </div>
        </div>
        <div class="col-2">
            qty:{{cart.quantity}}
            status:{{cart.status}}
        </div>
        <div class="col-2">
            {%if cart.status != "order placed"%}
            <a href="{%url 'place-order' cart.id cart.product.id %}" class="btn btn-outline-success">Checkout</a>

            {%endif%}
            <a href="{%url 'cart-remove' cart.id  %}" class="btn btn-outline-danger">Remove</a>

        </div>
        {%endfor%}

    </div>
</div>
{%endblock%}

customer/templates/cart-remove.html
{%extends 'base.html'%}
{%block body_block%}
<div class="container-fluid">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            {%if messages%}
            {%for m in messages%}
            {% if m.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>{{m}}</strong> You should check in on some of those fields below.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {%endif%}
            {%endfor%}
            {%endif%}
        </div>
        <div class="col-4"></div>
    </div>
    <div class="row">
        {%for cart in carts%}
        <div class="col-4"></div>
        <div class="col-4">
            <div class="card h-100">
                <!-- Product image-->
                <img class="card-img-top" src="{{cart.product.image.url}}" height="100%" width="100%" alt="..."/>
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{cart.product.product_name}}</h5>
                        <!-- Product price-->
                        Rs.{{cart.product.price}}/-
                    </div>
                </div>

            </div>
        </div>
        <div class="col-2">
            qty:{{cart.quantity}}
            status:{{cart.status}}
        </div>
        <div class="col-2">
            <a href="" class="btn btn-outline-success">Checkout</a>
            <a href="" class="btn btn-outline-danger">Remove</a>

        </div>
        {%endfor%}

    </div>
</div>
{%endblock%}

customer/templates/home.html
{%extends 'base.html'%}
{%block body_block%}
<div class="container-fluid">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            {%if messages%}
            {%for m in messages%}
            {{m}}
            {%endfor%}
            {%endif%}
        </div>
        <div class="col-4"></div>

    </div>
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {%for product in products%}

        <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{product.image.url}}" alt="..." >
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{product.product_name}}</h5>
                                    <!-- Product price-->
                                    ${{product.price}}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{%url 'product-detail' product.id%}">View</a></div>
                            </div>
                        </div>
                    </div>

        {%endfor%}
    </div>
</div>
{%endblock%}

customer/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
 <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            {%if messages%}
            {%for m in messages%}
            {% if m.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>{{m}}</strong> You should check in on some of those fields below.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {%endif%}
            {%endfor%}
            {%endif%}
        </div>
        <div class="col-4"></div>
    </div>
    <div class="row mt-5">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="post">
                {%csrf_token%}
                {{form.as_p}}
                <button type="submit" class="btn btn-outline-info">Login</button>
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>
</body>
</html>

customer/templates/place-order.html
{%extends 'base.html'%}
{%block body_block%}
<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">

        </div>
        <div class="col-2"></div>
    </div>
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="post">
                {%csrf_token%}
                {{form.as_p}}
                <button type="submit">Add</button>
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>
{%endblock%}

customer/templates/product-detail.html
{%extends 'base.html'%}
{%block body_block%}
<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{product.image.url }}" alt="..." height="500px"/>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">
                                        {{product.product_name}}

                                    </h5>
                                    <!-- Product price-->
                                    ${{product.price}}
                                    <p>{{product.description}}</p>
                                    <p>{{product.category}}</p>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{%url 'addto-cart' product.id%}">Add To Cart </a></div>
                            </div>
                        </div>
                    </div>
        </div>
        <div class="col-3"></div>
    </div>
</div>
{%endblock%}

customer/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="row mt-5">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="post">
                {%csrf_token%}
               {{form.as_p}}
                <button type="submit" class="btn btn-outline-info">Register</button>
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>
</body>
</html>